name: .NET Security Scan

on:
  workflow_dispatch:
  schedule:
  - cron: "1 0 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Install Aspire
      run: dotnet workload install aspire
    - name: Restore dependencies
      run: dotnet restore
    - name: Scan for security vulnerabilities
      run: |
        dotnet list package --vulnerable --include-transitive | tee vulnerable.txt
        sh -c "! grep 'has the following vulnerable packages' vulnerable.txt"
